### ISSUE TITLE
Missing support for Remark field

### ISSUE THREAD

**Issue by JBtje** [myparcelnl/sdk#177]
In the PostNL API, you can set the "Remark" field under Address type. [PostNL API](https://developer.postnl.nl/browse-apis/send-and-track/labelling-webservice/documentation/)

```
Remark | O(ptional) | String [0-35] | Remark of the shipment | Fragile
```

The SDK ReadMe refers to `setDeliveryRemark()` (Line 294), however the source does not contain this method...

If would be nice if the Remark field can be supported, so we can add some extra text to the label ment for the receiver.

**Comment by RichardPerdaan** [comment]
Dear @JBtje ,

Thank you for reporting this issue. 
It is strange that the `setDeliveryRemark()` is mentioned in the documentation because the source does not contain this method. Therefore I will discuss this with my colleague to remove it in the documentation. 

Perhaps the `setLabelDescription()` method is the solution for you. With this you can add some extra description on the label.

**Comment by JBtje** [comment]
I tested the Remark field with PostNL API, however it is not shown on "Brievenbus" packages. I'll give `setLabelDescription()` a try, thank you!

**Comment by RichardPerdaan** [comment]
if the `setLabelDescription()` does not give the correct results, you can always open the issue again.
